### ISSUE TITLE
Log exceptions 

### ISSUE THREAD

**Issue by xPlutox** [rulebook-rules/rulebook#124]
In RuleAdapter.mapFactsToProperties exceptions are swallowed. They should be logged to get a better view on the initial problem.

**Comment by Clayton7510** [comment]
Branch off the develop branch and issue a PR. Agreed that logging could be more robust.

**Comment by xPlutox** [comment]
@Clayton7510 can you add me as collaborator pls? I'm not able to create branches at the moment.

**Comment by Clayton7510** [comment]
Thanks for the PR! I'll complete the review after work today.
You don't need to create a branch. You can just fork, make updates and then issue a PR. Actually, that's the route I am going to follow going forward, too.

Prior to release, I will, however, update the collaborators in the Maven POM to include you as a collaborator so that credit is attributed to your contribution.
