### ISSUE TITLE
Facts of different actual types

### ISSUE THREAD

**Issue by TenYearsGone** [rulebook-rules/rulebook#70]
Is it possible to use a Java interface and/or a general class (instead of the concrete type) as the generic type passed to Facts and FactMap and the @Given List?  I replaced references to ApplicantBean with an interface (IApplicant which declares the expected methods) e.g.  FactMap<IApplicant > and in the rule: 
@Given private List<IApplicant > applicants 
I end up with no objects in the applicants list. I've tried this with a generalized class as well (where concrete classes are specializations of ApplicantBean).

**Comment by Clayton7510** [comment]
If you specify a List with a generic type under a Given annotation then it should be populated. Similarly, if you specify a FactMap, that should also be populated. 

I'll post a working example tomorrow.
Sorry for the delayed response.

**Comment by Clayton7510** [comment]
If we take the First Time Homebuyer POJO rule from the Megabank example:

```java
@Rule(order = 4)
public class FirstTimeHomeBuyerRule {
  @Given
  List<ApplicantBean> applicants;

  @Result
  private double rate;

  @When
  public boolean when() {
    return
        applicants.stream().anyMatch(applicant -> applicant.isFirstTimeHomeBuyer());
  }

  @Then
  public void then() {
    rate = rate - (rate * 0.20);
  }
}
```

If you do not include the type in the List, then you are correct, you the List will not be injected. And that is true for all collection types: List, Set, Map... The generic type must be specified for it to be injected. But Let's assume you want all facts injected into a collection annotated by Given. that can be done with annotating NameValueReferableMap with Given. The rule above could therefore be changed to the following:

```java
@Rule(order = 4)
public class FirstTimeHomeBuyerRule {
  @Given
  FactMap facts;

  @Result
  private double rate;

  @When
  public boolean when() {
    return facts.values().stream().anyMatch(applicant -> 
            ((NameValueReferable)applicant).getValue() instanceof ApplicantBean &&
            ((NameValueReferable<ApplicantBean>)applicant).getValue().isFirstTimeHomeBuyer());
  }

  @Then
  public void then() {
    rate = rate - (rate * 0.20);
  }
}
```

Since FactMap is an implementation of NameValueReferableMap, this works. It's not nearly as elegant as using a List of the types of facts you want, but if you want to peel back the covers a bit and get access to everything, this will do it. And perhaps in some cases, you might want access to every fact regardless of type.

**Comment by TenYearsGone** [comment]
Thank you for the help and example.
