### ISSUE TITLE
Different Fact types in one FactMap

### ISSUE THREAD

**Issue by wheezymustafa** [rulebook-rules/rulebook#75]
Hello again.

Is it possible to include multiple object types in one FactMap, after setting the FactType in the ruleBuilder? Example:

I'm first building the rule with a FactType of Deduction.class:

`  private RuleBuilder<Deduction,Boolean> getDeductionRuleBuilder(){
    return RuleBuilder.create().withFactType(Deduction.class).withResultType(Boolean.class);
  }
`

When I setup my FactMap, I have a Deduction and String object I want to pass in:
`  private NameValueReferableMap getFactMap(Deduction deduction, String state) {
    NameValueReferableMap facts = new FactMap<>();
    facts.setValue("deduction", deduction);
    facts.setValue("state", state);
    return facts;
  }`

Here's an example rule I have defined:
`
    addRule(getDeductionRuleBuilder()
      .when(facts -> facts.getOne().getType().equals(SOME_EQUALITY_CHECK))
      .then((factMap, booleanResult) -> {
        System.out.println(factMap.getStrVal("state"));
        booleanResult.setValue(Constants.SOME_OTHER_CHECK.contains(factMap.getStrVal("state")));
      }).stop().build());
`
So, when I execute the Rule, obviously the Deduction fact is retained, however the String object seems to get cut out of the factmap, and it returns false because it can't evaluate the "state" Fact.  I realize I could easily create a container object to hold the Deduction and String object.  However, I wanted to make sure there was no other way to create a FactMap of various object types to be used in a RuleBook.

**Comment by Clayton7510** [comment]
It is possible. 

Instead of 
```java
RuleBuilder.create().withFactType(Deduction.class).withResultType(Boolean.class);
```
you can do this
```
 RuleBuilder.create().withResultType(Boolean.class);
```
Using your example, the return type of getDeductionRuleBuilder would then be RuleBuilder<Object, Boolean>.

Adding the rule would then look like this
```java
addRule(getDeductionRuleBuilder() .when(facts -> facts.getValue("deduction").getType().equals(SOME_EQUALITY_CHECK)) .then((factMap, booleanResult) -> { System.out.println(factMap.getStrVal("state")); booleanResult.setValue(Constants.SOME_OTHER_CHECK.contains(factMap.getStrVal("state"))); }).stop().build());
```

The issue you were running into is when you restrict a rule to a specific fact type, only facts of that type are available to the rule. If you want the rule to have all the facts given to the rulebook available, then don't specify a fact type. That's actually an intentional thing that allows you to think of rules in terms of a specific type of fact. Of course, sometimes you may want a rule to access multiple fact types. And in that case, just don't specify a fact type for the rule.
