### ISSUE TITLE
Unable to create an instance of the specified Rule class <> with fact and result type specified.

### ISSUE THREAD

**Issue by wheezymustafa** [rulebook-rules/rulebook#88]
Hello, just moved to 0.8 from 0.7.  Prior to and after the update, I'm getting these debug statements in my output when trying to build rules.  However, the rules are being loaded and executed properly as all my testing is passing successfully.  I've tried different variations of below and still end up with the log statements.  Any ideas?

**14:30:59.143 [main] DEBUG c.d.rulebook.lang.RuleBuilder - Unable to create an instance of the specified Rule class 'class com.deliveredtechnologies.rulebook.model.GoldenRule' with fact and result types specified**

`public class CanadaRules extends CoRRuleBook<BusinessRulesResult>{

 Override
  protected void defineRules() {
    addRule(getCalculatorRuleBuilder()
      .when(fact -> isRequestTypeDonation(fact.getOne()))
      .then((fact, result) -> {
        Map<Item,List<Tax>> appliedItemRateMap = getAppliedItemRateMap(fact.getOne());
        result.setValue(createResult(appliedItemRateMap));
      }).stop().build());

  private RuleBuilder<CalculatorFact, BusinessRulesResult> getCalculatorRuleBuilder() {
    return RuleBuilder.create().withFactType(CalculatorFact.class).withResultType(BusinessRulesResult.class);
  }
  }`

**Comment by Clayton7510** [comment]
RuleBuilder builds Rules of type GoldenRule by default. Since you could implement your own Rule, instead of using the default GoldenRule, it uses reflection to create an instance of the Rule implementation. One of the possible constructors accepts a Fact type and a Result type, which GoldenRule doesn't use. If that constructor fails then it moves on to a constructor that just specifies the Fact type, which GoldenRule does use. And since you got a debug instead of an error log, it likely worked as expected.

The change that you are seeing is the addition of some debug logging. If you turn off the debug logging level (maybe set it to INFO + WARN + ERROR + FATAL), then that should resolve your issue.

**Comment by Clayton7510** [comment]
I suppose a good question might be "Why does RuleBuilder look for a constructor that accepts a Fact type and a Result type if GoldenRule doesn't even implement that constructor?" I think the original thought is that GoldenRule would have such a constructor. But since it doesn't and probably won't, it might be worth evaluating whether or not that logic should be changed in a future release. But in the meantime, it's not hurting anything ;)

**Comment by wheezymustafa** [comment]
Yes this answers my question, thank you!
