### ISSUE TITLE
RuleState vs RuleChainActionType

### ISSUE THREAD

**Issue by wheezymustafa** [rulebook-rules/rulebook#89]
Can you explain what the expected behavior would be for setting RuleState to next/break vs setting the RuleChainActionType to continue/stop on failure?  I noticed setting STOP_ON_FAILURE automatically sets the rule to RuleState.NEXT.  Just looking for some clarity on these values.

**Comment by Clayton7510** [comment]
By default a rule is set to RuleChainActionType.CONTINUE_ON_FAILURE. That means that the rule chain will continue (i.e. the next rule in the chain will be evaluated) if the rule's "when" condition evaluates to false or if there is an error evaluating the rule. The rule is then, in effect, skipped. However, the rule chain will break if and only if the RuleState is set to BREAK (e.g. if the stop() method is used in the RuleBuilder), the rule's condition evaluates to true and there is no error when evaluating the rule. This was the only behavior of rules in RuleBook prior to v0.8 and it is now the default behavior.

If a rule is set to RuleChainActionType.STOP_ON_FAILURE then if the rule's condition evaluates to false or an error is thrown while RuleState is BREAK, the rule chain is broken. However, if the rule's condition (aka "when") evaluates to true without error, the rule chain continues. It's basically a way to break the rule chain on a failed rule.

What you saw in the code where STOP_ON_FAILURE sets the rule to RuleState.NEXT is a way of ensuring that the rule chain continues with STOP_ON_FAILURE set and the rule evaluating to true. It was done like that so that it could work with the existing rule chain logic in the CoRRuleBook.

**Comment by wheezymustafa** [comment]
Thank you for the explanation
